drop table booking;
drop table comments;
drop table items;
drop table item_request;
drop table users;


CREATE TABLE IF NOT EXISTS users
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(100),
    email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS item_request
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(200),
    user_id     INTEGER references users (id),
    created     TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(200),
    available   BOOLEAN,
    owner_id    INTEGER references users (id),
    request_id  INTEGER references item_request (id)
);

CREATE TABLE IF NOT EXISTS booking
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP,
    end_date   TIMESTAMP,
    item_id    INTEGER references items (id),
    user_id    INTEGER references users (id),
    status     VARCHAR(8)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(200),
    item_id   INTEGER references items (id),
    author_id INTEGER references users (id)
);